### PR TITLE
Feat: Setup CRUD for games and added Simple_form

### PR DESCRIPTION
**Pull request by lisarics**
This is the basic setup but I think we need to add a field for Id to the database.  There is a starter form in the view for New Game.

### CODE REVIEW

**Comment by tinaylee** [comment]
Thanks Lisa!  Will review your branch tomorrow.  As far as the id field goes, rails automatically creates the id field so it isn't in the migration file but it actually already exists

**Comment by lisarics** [comment]
Thanks Tina.  As soon as I read your comment I thought " oh yeah, I knew that " :)

**Review by twbeasley — APPROVED** [review]
Everything looks great to me.  Merge whenever you are ready.

**Comment by tinaylee** [comment]
I tested the branch and everything is working great.  Please merge when you're ready

**Review by tinaylee — APPROVED** [review]
Everything looks great, thanks Lisa!

**Pull request merged**
