### PR TITLE
ChessPiece class contains is_obstructed method

### PR DESCRIPTION
**Pull request by jakekarl3**
- is_obstructed method takes in the board array, current_position, and new_position array values
- board array assumed to be an 8x8 array. Index with a piece located there contains the piece id and an empty space contains 'nil'
- current_position=[x, y]
- new_position=[x, y]

### CODE REVIEW

**Review by lisarics — APPROVED** [review]
Looks like you got this.

**Comment by tinaylee** [comment]
Logic looks sound, my only comment is that this one method is 149 lines long.  It will be more manageable to break invalid, horizontal, vertical, and diagonal moves into their own methods and call those methods in is_obstructed?

**Comment by jakekarl3** [comment]
Yah I knew it had to be broken up from how it is now. I had my mentor session today and he helped walk me through how we could break it up in to a bunch of smaller methods. I'll try to break it down and make it much smaller, more manageable methods

**Comment by jakekarl3** [comment]
I reworked the entire is_obstructed? method. I think it should be much easier to follow and reuse portions as needed.

**Pull request merged**
